# Generated by Django 6.0.3 on 2026-03-17 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaliberGauge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('caliber_gauge', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Caliber/Gauge',
                'verbose_name_plural': 'Calibers/Gauges',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Firearm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('manufacturer_importer', models.CharField(blank=True, max_length=200, verbose_name='Manufacturer/Importer')),
                ('model', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='Serial Number')),
                ('date_acquired', models.DateField(blank=True, verbose_name='Date Acquired')),
                ('cost', models.CharField(blank=True, max_length=200)),
                ('purchase_location', models.CharField(blank=True, max_length=200, verbose_name='Purchase Location')),
                ('sold_transferred_to', models.CharField(blank=True, max_length=200, verbose_name='Sold/Transferred to')),
                ('caliber_gauge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firearms.calibergauge', verbose_name='Caliber/Gauge')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firearms.type')),
            ],
            options={
                'verbose_name': 'Firearm',
                'verbose_name_plural': 'Firearms',
            },
        ),
    ]
