# Generated by Django 6.0.3 on 2026-03-17 22:11

from django.db import migrations


def init_types(apps, schema_editor):
    types = [
        "Frame",
        "Other",
        "Pistol",
        "Receiver",
        "Revolver",
        "Rifle",
        "SBR",
        "Shotgun",
        "Silencer"
    ]

    for type in types:
        apps.get_model("firearms", "Type").objects.create(
            type = type
        )

def init_calibers_gauges(apps, schema_editor):
    calibers_gauges = [
        ".22 Long Rifle",
        ".223 Remington",
        ".30 CAL",
        ".300 AAC Blackout",
        ".380 ACP",
        ".40 S&W",
        ".45 ACP",
        "12 Gauge",
        "5.45x39mm",
        "5.56x45mm",
        "6.5mm Creedmoor",
        "7.62x39mm",
        "9x19mm",
        "Multi"
    ]

    for caliber_gauge in calibers_gauges:
        apps.get_model("firearms", "CaliberGauge").objects.create(
            caliber_gauge = caliber_gauge
        )

class Migration(migrations.Migration):

    dependencies = [
        ('firearms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_types),
        migrations.RunPython(init_calibers_gauges),
    ]
